### PR TITLE
feat: port comment

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by scooter-dangle** [comment]
Thanks for the PR! Sorry for not responding earlier! Will try to look at this in the next day or so.

**Comment by pickfire** [comment]
Okay, updated with tests.

**Comment by pickfire** [comment]
Any news on this?

**Comment by scooter-dangle** [comment]
Note: rebased to include formatting fix to pass CI (had thought the fix was in master...should have fixed it there first in retrospect)

**Pull request merged**
